# Assignment 1 IRS

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [14]:
# required imports
import numpy as np
import fnmatch
import os


Suppose we have 3 files containing data :

### File Contents

<img src="1.png"/>
<img src="2.png"/>
<img src="3.png"/>

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [15]:
# Here we have intialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set


In [16]:
#Your code starts here   
files_names = [os.path.join(".", "files", f) for f in os.listdir("./files")]

file_count = len(files_names)
files_dict = {name:ID for ID,name in enumerate(files_names)}
#Your code ends here       

Displaying the count of files.

In [17]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 3


Displaying Dictionary containing all files.

In [18]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'./files/f3.txt': 0, './files/f2.txt': 1, './files/f1.txt': 2}


# Step 3 Extract Unique Vocabulary

In [19]:
# write code to print all the unique words in every file and store them in a set

In [20]:
#Your code starts here    
for path in files_dict.keys():
    fhand = open(path)
    unique_word_set.update(fhand.read().split())
    fhand.close()

print("\nunique words in files\n", unique_word_set)
print("\ncount of files ", file_count)
#Your code ends here


unique words in files
 {'this', 'This', 'book', 'pen', 'my', 'is', 'My', 'interesting'}

count of files  3


### Expected Output

<img src="4.png"/>

# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

In [21]:
# Create Term doc matrix such that colmns will be unique words and all the files will be rows
# Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [22]:
#Your code starts here    
TERM_DOC_MATRIX = np.zeros( (file_count, len(unique_word_set)) )
print("TERM_DOC_MATRIX initially\n", TERM_DOC_MATRIX)

words_dict = {word:ID for ID,word in enumerate(unique_word_set) }
print("\nDictionary of unique words\n", words_dict)

print("\nDictionary of files\n", files_dict)
#Your code ends here

TERM_DOC_MATRIX initially
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

Dictionary of unique words
 {'this': 0, 'This': 1, 'book': 2, 'pen': 3, 'my': 4, 'is': 5, 'My': 6, 'interesting': 7}

Dictionary of files
 {'./files/f3.txt': 0, './files/f2.txt': 1, './files/f1.txt': 2}


### Expected Output

<img src="5.png"/>

# Step 5 Fill Term Document Matrix

In [23]:
# Fill the term doc matrix by checking if the unique word exists in a file or not
# If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
# Do the same for all the files present in the directory

In [24]:
#Your code starts here    
for path in files_dict.keys():
    fhand = open(path)
    words = fhand.read().split()
    for w in words:
        if w in unique_word_set:
            TERM_DOC_MATRIX[ files_dict[path] ][ words_dict[w] ] = 1
    
    fhand.close()

#Your code ends here

### Expected Output

<img src="6.png"/>

# Step 6 Ask for a user Query

In [25]:
# For user query make a column vector of length of all the unique words present in a set

In [26]:
#Your code starts here    
col_vector = np.zeros( (len(unique_word_set),1) ) 
print("col_vector intitally\n", col_vector)

#Your code ends here

col_vector intitally
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

<img src="7.png"/>

In [27]:
query = input("\nWrite something for searching  ")
# Check every word of query if it exists in the set of unique words or not
# If exixts then increment the count of that word in word dictionary



Write something for searching  


In [28]:
#Your code starts here    
words = query.split()
for w in words:
    if w in unique_word_set:
        col_vector[words_dict[w], 0] = 1

#Your code ends here

### Expected Output

<img src="8.png"/>

# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [29]:
#Your code starts here  
resultant_vector = TERM_DOC_MATRIX.dot(col_vector)
print(resultant_vector, "\n")

maximum = np.amax(resultant_vector)
print("Maximum in resultant is ", maximum, "\n")

index = list(resultant_vector).index(maximum)
print("Index of maximum in resultant is ", index )

#Your code ends here

[[0.]
 [0.]
 [0.]] 

Maximum in resultant is  0.0 

Index of maximum in resultant is  0


### Expected Output

<img src="9.png"/>

# Step 8 Display the contents of file


In [30]:
#Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [31]:
#Your code starts here    

if maximum != 0:
    path =  list(files_dict)[index]
    print("Best match: ", path, "\n" )
    fhand = open(path)
    print(fhand.read())
    fhand.close()
else:
    print("Sorry, No match!")
#Your code ends here

Sorry, No match!


Congratulations Now you are able to build your own small IRS.